# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’

target 'TwoFlowerSelection_objc' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for TwoFlowerSelection_objc

pod 'AVOSCloud'               # 数据存储、短信、云引擎调用等基础服务模块
pod 'AVOSCloudIM'             # 实时通信模块
pod 'AVOSCloudCrashReporting' # 错误报告模块

end
